[package]
name = "t-weather"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
crossterm = "0.28.1"
reqwest = { version = "0.12.7", features = ["blocking"]}
serde = { version = "1.0.210", features = ["derive"]}
tui = "0.19.0"
